version: "3.0"
services:
  odoo:
    restart: always
    container_name: odoo
    build:
      context: ./odoo/
      args:
        - GIT_BRANCH=13.0
        - ODOO_VERSION=13.0
    ports:
      - "8069:8069"
      - "8072:8072"
    expose:
      - "8069"
      - "8072"
    env_file:
      .env
    volumes:
      - odoo-web-data:/var/lib/odoo
    command: odoo

  nginx:
    restart: always
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    links:
      - odoo:odoo

volumes:
  odoo-web-data:
